### ISSUE TITLE
一样的代码，你是博主本人吗？

### ISSUE THREAD

**Issue by robindon** [lyyyuna/anotherDebugger#1]
[如何开发自己的调试器](http://www.cppblog.com/weiym/archive/2013/03/12/198350.html)
对系统原理和程序运行过程的理解，会熟练使用调试器是一个层次，能单独开发调试器又是另外一个层次。
下面是一个不错的系列，告诉你如何自己开发一款微型调试器， 记录一下，以后可能用得着...

[一个调试器的实现（一）调试事件与调试循环](http://www.cnblogs.com/zplutor/archive/2011/03/04/1971279.html)
[一个调试器的实现（二）调试事件的处理](http://www.cnblogs.com/zplutor/archive/2011/03/06/1972540.html)
[一个调试器的实现（三）异常](http://www.cnblogs.com/zplutor/archive/2011/03/08/1977702.html)
[一个调试器的实现（四）读取寄存器和内存](http://www.cnblogs.com/zplutor/archive/2011/03/13/1983010.html)
[一个调试器的实现（五）调试符号](http://www.cnblogs.com/zplutor/archive/2011/03/20/1989783.html)
[一个调试器的实现（六）显示源代码](http://www.cnblogs.com/zplutor/archive/2011/03/27/1997198.html)
[一个调试器的实现（七）断点](http://www.cnblogs.com/zplutor/archive/2011/04/02/2004097.html)
[一个调试器的实现（八）单步执行](http://www.cnblogs.com/zplutor/archive/2011/04/09/2010707.html)
[一个调试器的实现（九）符号模型](http://www.cnblogs.com/zplutor/archive/2011/04/14/2015864.html)
[一个调试器的实现（十）显示变量](http://www.cnblogs.com/zplutor/archive/2011/04/22/2025190.html)
[一个调试器的实现（十一）显示函数调用栈](http://www.cnblogs.com/zplutor/archive/2011/04/23/2025549.html)

**Comment by lyyyuna** [comment]
@robindon 不是，我改成了 cpp 版本
